# Generated by Django 4.0.3 on 2022-07-18 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadImages', models.ImageField(blank=True, upload_to='memo/images/%Y/%m/%d/')),
                ('uploadFile', models.FileField(blank=True, upload_to='memo/files/%Y/%m/%d/')),
                ('memo', models.CharField(max_length=1000)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
