# Generated by Django 4.0.3 on 2022-07-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteType', models.CharField(max_length=50)),
                ('deviceType', models.CharField(max_length=10)),
                ('prioritize', models.IntegerField()),
                ('writer', models.CharField(max_length=20)),
                ('request', models.CharField(max_length=20)),
                ('manager1', models.CharField(max_length=20)),
                ('manager2', models.CharField(max_length=20)),
                ('taskName', models.CharField(max_length=255)),
                ('referenceUrl', models.CharField(max_length=255, null=True)),
                ('taskContent', models.CharField(max_length=3000, null=True)),
                ('completeState', models.CharField(max_length=1)),
                ('completeDate', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=3000, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
