# Generated by Django 4.0.3 on 2022-07-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='comment',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
