# Generated by Django 4.0.3 on 2022-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_writer_remove_taskcomment_writer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='manager1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='manager2',
        ),
        migrations.AddField(
            model_name='task',
            name='manager',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='deviceType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioritize',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='siteType',
            field=models.CharField(max_length=255),
        ),
    ]
