# Generated by Django 4.0.3 on 2022-07-19 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_devicetype_manager_sitetype_remove_task_devicetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completeState',
            new_name='taskState',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completeDate',
        ),
        migrations.AddField(
            model_name='task',
            name='taskEndDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='taskProgress',
            field=models.IntegerField(default=0, help_text='0~100사이 값으로 입력하세요.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='task',
            name='taskStartDate',
            field=models.DateTimeField(null=True),
        ),
    ]
