# Generated by Django 4.0.3 on 2022-06-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('httpHost', models.CharField(max_length=255)),
                ('httpUrl', models.CharField(max_length=255)),
                ('parameter', models.CharField(max_length=3000, null=True)),
                ('httpReferer', models.CharField(max_length=1000, null=True)),
                ('remoteAddr', models.CharField(max_length=255)),
                ('localAddr', models.CharField(max_length=255)),
                ('httpUserAgent', models.CharField(max_length=255)),
                ('httpMethod', models.CharField(max_length=255)),
                ('httpCookie', models.CharField(max_length=3000)),
                ('errorNumber', models.IntegerField()),
                ('errorCategory', models.CharField(max_length=255)),
                ('errorDescription', models.CharField(max_length=1000)),
                ('errorCol', models.IntegerField()),
                ('errorLine', models.IntegerField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
