# Generated by Django 4.0.3 on 2022-06-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=3000)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('siteErrorLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.siteerrorlog')),
            ],
        ),
    ]
