# Generated by Django 4.0.3 on 2022-07-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteerrorlog',
            name='errorStatus',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
